### ISSUE TITLE
Error upon npm install where `main.wasm` not found

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/wasm-sqlparser#31]
**Describe the bug**
After installing this package, importing it, and initializing it (per the instructions), an error is thrown, noting that `./main.wasm` is not found. It looks to be an issue via [`main.js`](https://github.com/tablelandnetwork/wasm-sqlparser/blob/8b0cdd9a952919b78f4ce341fe0082df39101621/main.js#L6) and the way it reads to file.

**To Reproduce**

1. Install this package: `npm i @tableland/sqlparser`
2. Import and initialize it into your Node project, as defined in the README (i.e., import, then call `init()`)
3. The following error is thrown upon running the project (note: using this in a file in a project file called query.js):
```
node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './main.wasm'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at init (file:///Users/db/tbl/tablebot/node_modules/@tableland/sqlparser/main.js:7:16)
    at file:///Users/db/tbl/tablebot/commands/query.js:5:7
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './main.wasm'
}
```

**Expected behavior**
No errors upon installing and simply importing into my project. [Line 6 in `main.js`](https://github.com/tablelandnetwork/wasm-sqlparser/blob/8b0cdd9a952919b78f4ce341fe0082df39101621/main.js#L6) is causing the issue: `input = fs.readFileSync("./main.wasm")` since I think it's looking at the local directory and not relative to the project I'm importing it into. Here's a simple fix that resolves the issue:
```
const filePath = new URL('./main.wasm', import.meta.url);
input = fs.readFileSync(filePath);
```

**Desktop (please complete the following information):**

- OS: Mac M1
- Node v18.7.0

**Comment by dtbuchholz** [comment]
Closed with https://github.com/tablelandnetwork/wasm-sqlparser/pull/32
